"""Windy Fly Quickstart — the ``windy go`` command.

ADR-059: there is one hallway. ``windy go`` opens the Windy hatch ceremony
in the browser (``windyfly.hub_hatch``); the agent is born there. The old
terminal hatch (key paste, ``--keyless`` kiosk, CLI-side Matrix/mail/phone
provisioning, terminal birth certificate) was removed in 0.7.5.

This module also keeps the config writers that other commands reuse
(``windy bring-home`` writes the keyless Windy Mind config).
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path
from typing import Any

from rich.console import Console

from windyfly.eternitas.url import eternitas_env_line
from windyfly.platform import get_project_root
from windyfly.provider_defaults import PROVIDER_DEFAULTS, key_detection_order

logger = logging.getLogger(__name__)
console = Console()
PROJECT_ROOT = get_project_root()


# ═══════════════════════════════════════════════════════════════════════
# Key detection — identify provider from key format
# ═══════════════════════════════════════════════════════════════════════

# Single source of truth: windyfly.provider_defaults (Sprint 2 —
# this table used to be one of THREE divergent copies; see that
# module's docstring, imported at top of file). Dict shapes preserved
# for downstream callers.
KEY_PATTERNS: list[dict[str, str]] = [
    {
        "prefix": p["key_prefix"],
        "env_var": p["env_var"],
        "provider": p["name"],
        "model": p["default_model"],
        "url": p["url"],
    }
    for p in key_detection_order()
]

# Providers the user can choose if we can't auto-detect
PROVIDER_MENU = [
    {
        "name": p["name"],
        "env_var": p["env_var"],
        "model": p["default_model"],
        "url": p["url"],
    }
    for p in PROVIDER_DEFAULTS
]


def detect_provider(key: str) -> dict[str, str] | None:
    """Identify the provider from an API key's prefix.

    Returns a dict with provider, env_var, model, url — or None if
    the key format isn't recognized.
    """
    key = key.strip()
    for pattern in KEY_PATTERNS:
        if key.startswith(pattern["prefix"]):
            return pattern
    return None


# ═══════════════════════════════════════════════════════════════════════
# Config writer (reuses setup_wizard's format)
# ═══════════════════════════════════════════════════════════════════════


# The agent's identity lives in .env. Re-running `windy go` rewrites .env
# from scratch, which blanked ETERNITAS_PASSPORT_TOKEN — the next hatch then
# minted a SECOND passport for the same agent (Eternitas caps auto-hatch at
# 5/hour, and the first passport was orphaned). Keep these across rewrites.
_IDENTITY_KEYS = ("ETERNITAS_PASSPORT", "ETERNITAS_PASSPORT_TOKEN")


def _read_env_values(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                k, v = line.split("=", 1)
                values[k.strip()] = v.strip()
    except OSError:
        pass
    return values


def _write_env_keeping_identity(env_lines: list[str]) -> None:
    env_file = PROJECT_ROOT / ".env"
    kept = {
        k: v for k, v in _read_env_values(env_file).items()
        if k in _IDENTITY_KEYS and v
    }
    out: list[str] = []
    for line in env_lines:
        key = line.split("=", 1)[0] if "=" in line else ""
        if key in kept:
            out.append(f"{key}={kept.pop(key)}")
        else:
            out.append(line)
    out.extend(f"{k}={v}" for k, v in kept.items())
    from windyfly.platform import write_private_text

    write_private_text(env_file, "\n".join(out) + "\n")



def write_quick_config(
    env_var: str,
    api_key: str,
    model: str,
    preset: str = "buddy",
) -> None:
    """Write .env and windyfly.toml for quickstart."""
    from windyfly.setup_wizard import PRESETS, PROVIDERS

    preset_data = PRESETS.get(preset, PRESETS["buddy"])
    data_dir = PROJECT_ROOT / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    # Build .env
    env_lines = [
        "# Windy Fly — generated by `windy go`",
        f"DEFAULT_MODEL={model}",
        "",
        "# LLM Providers",
    ]
    for provider in PROVIDERS:
        if provider["key"] == env_var:
            env_lines.append(f"{provider['key']}={api_key}")
        else:
            env_lines.append(f"{provider['key']}=")

    env_lines.extend([
        "",
        "# Database",
        "WINDYFLY_DB_PATH=data/windyfly.db",
        "",
        "# Logging",
        "LOG_LEVEL=INFO",
        "",
        "# Matrix / Windy Chat (optional)",
        "MATRIX_HOMESERVER=https://chat.windychat.ai",
        "# MATRIX_BOT_USER: leave empty; the agent's own @agent_<passport> id comes from its passport",
        "MATRIX_BOT_USER=",
        "MATRIX_BOT_TOKEN=",
        "MATRIX_BOT_PASSWORD=",
        "",
        "# Windy Pro API (optional)",
        "WINDY_API_URL=http://localhost:8098",
        "WINDY_JWT=",
        "",
        "# Eternitas (agent identity: passport, birth certificate, trust)",
        eternitas_env_line(),
    ])

    _write_env_keeping_identity(env_lines)

    # Build windyfly.toml
    agent_name = os.environ.get("WINDYFLY_AGENT_NAME", "Windy Fly")
    toml_content = f"""[agent]
name = "{agent_name}"
default_model = "{model}"
max_context_tokens = 8000
max_response_tokens = 2000
temperature = 0.7

[memory]
db_path = "data/windyfly.db"
max_episodes_per_context = 20
max_nodes_per_context = 10

[personality]
soul_path = "SOUL.md"
preset = "{preset}"
humor_level = {preset_data.get('humor', 5)}
formality = {preset_data.get('formality', 5)}
proactivity = 5
verbosity = 5
reasoning_depth = 6
autonomy = 3
epistemic_strictness = 5

[costs]
daily_budget_usd = 5.0
warn_at_usd = 0.50

[matrix]
homeserver = "https://chat.windychat.ai"
# No bot_user: each agent's Matrix id is its own @agent_<passport>, minted at
# hatch from its passport and confirmed at login. Set bot_user only for a
# self-hosted password login.

[windy_api]
base_url = "http://localhost:8098"
"""
    (PROJECT_ROOT / "windyfly.toml").write_text(toml_content, encoding="utf-8")


#: The model sentinel for keyless agents. Windy Mind resolves it to a
#: free model for a free-tier caller (its free-auto routing, live since
#: 2026-07-04). If Mind is unreachable there's no paid provider to fall
#: to — the agent drops to the Ollama lifeboat, the correct degradation
#: for a no-key agent.
KEYLESS_MODEL = "windy-mind-auto"


def write_keyless_config(preset: str = "buddy") -> None:
    """Write .env + windyfly.toml for a KEYLESS agent (Sprint 5).

    No API key. The brain is Windy Mind's free-compute lane, reached
    with the Eternitas Passport Token that hatch mints + persists (PR
    #247). Tools are enabled because Mind's tool-calling shipped
    2026-07-04 (PR #45) — without WINDY_MIND_SEND_TOOLS=1 the agent
    would skip Mind for any tool-bearing turn and could never act.
    """
    from windyfly.agent.models import MIND_DEFAULT_URL, MIND_URL_ENV
    from windyfly.setup_wizard import PRESETS

    preset_data = PRESETS.get(preset, PRESETS["buddy"])
    (PROJECT_ROOT / "data").mkdir(parents=True, exist_ok=True)

    env_lines = [
        "# Windy Fly — generated by `windy go` (keyless / Windy Mind brain)",
        f"DEFAULT_MODEL={KEYLESS_MODEL}",
        "",
        "# No API key needed — this agent thinks through Windy Mind's",
        "# free-compute lane, authenticated with its Eternitas passport.",
        # Canonical name + default come from the resolver every read site
        # uses, so the generated .env can't drift from what's read back.
        f"{MIND_URL_ENV}={MIND_DEFAULT_URL}",
        "WINDY_MIND_SEND_TOOLS=1",
        "",
        "# Eternitas (agent identity). ETERNITAS_PASSPORT_TOKEN is written here",
        "# by the hatch ceremony.",
        eternitas_env_line(),
        "ETERNITAS_PASSPORT_TOKEN=",
        "",
        "# Database",
        "WINDYFLY_DB_PATH=data/windyfly.db",
        "",
        "# Logging",
        "LOG_LEVEL=INFO",
        "",
        "# Matrix / Windy Chat (provisioned at hatch)",
        "MATRIX_HOMESERVER=https://chat.windychat.ai",
        "# MATRIX_BOT_USER: leave empty; the agent's own @agent_<passport> id comes from its passport",
        "MATRIX_BOT_USER=",
        "MATRIX_BOT_TOKEN=",
        "MATRIX_BOT_PASSWORD=",
    ]
    _write_env_keeping_identity(env_lines)

    agent_name = os.environ.get("WINDYFLY_AGENT_NAME", "Windy Fly")
    toml_content = f"""[agent]
name = "{agent_name}"
default_model = "{KEYLESS_MODEL}"
max_context_tokens = 8000
max_response_tokens = 2000
temperature = 0.7

[memory]
db_path = "data/windyfly.db"
max_episodes_per_context = 20
max_nodes_per_context = 10

[personality]
soul_path = "SOUL.md"
preset = "{preset}"
humor_level = {preset_data.get('humor', 5)}
formality = {preset_data.get('formality', 5)}
proactivity = 5
verbosity = 5
reasoning_depth = 6
autonomy = 3
epistemic_strictness = 5

[costs]
daily_budget_usd = 5.0
warn_at_usd = 0.50

[matrix]
homeserver = "https://chat.windychat.ai"
# No bot_user: each agent's Matrix id is its own @agent_<passport>, minted at
# hatch from its passport and confirmed at login. Set bot_user only for a
# self-hosted password login.

[windy_api]
base_url = "http://localhost:8098"
"""
    (PROJECT_ROOT / "windyfly.toml").write_text(toml_content, encoding="utf-8")


def is_keyless_configured() -> bool:
    """True if a keyless (Windy Mind) config is already written."""
    env_file = PROJECT_ROOT / ".env"
    if not env_file.exists():
        return False
    for line in env_file.read_text(encoding="utf-8").splitlines():
        if line.strip() == f"DEFAULT_MODEL={KEYLESS_MODEL}":
            return True
    return False


# ═══════════════════════════════════════════════════════════════════════
# The main event: windy go
# ═══════════════════════════════════════════════════════════════════════


def cmd_go(args: Any) -> None:
    """Hatch the agent: open the Windy hatch ceremony in the browser (ADR-059).

    The agent is born in the cloud and stays there; this terminal just
    opens the page and waits. There is no terminal hatch any more —
    ``WINDY_HATCH_VIA_HUB`` is ignored.
    """
    from windyfly import hub_hatch
    from windyfly.observability import disclosure

    disclosure.maybe_show(lambda line: console.print(f"[dim]{line}[/dim]"))
    force = bool(getattr(args, "force", False))
    if force:
        os.environ["_WINDYFLY_FORCE_HATCH"] = "1"

    rc = hub_hatch.go(
        console,
        force=force,
        open_browser=(lambda _url: None) if getattr(args, "no_browser", False) else None,
    )
    if rc:
        sys.exit(rc)
